name: Build Packer Image

on:
  workflow_dispatch: 
    inputs: 
      environment:
        description: 'Environment to build the image for'
        type: choice
        options:
          - Dev
        default: 'Dev'
jobs:
  packer:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Initialize Packer
        run: packer init packer-image.pkr.hcl

      - name: Set up credentials and keys
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" | base64 --decode > project-2024-2-e9ea57e25b7e.json
          echo "${{ secrets.SSH_KEY }}" | base64 --decode > ssh-key.pem
          chmod 600 ssh-key.pem
          ssh-keygen -y -f ssh-key.pem > ssh-key.pem.pub
          ls -la

      - name: Validate Packer template
        run: packer validate packer-image.pkr.hcl

      - name: Build Packer image
        env:
          PKR_VAR_gcp_credentials_path: "project-2024-2-e9ea57e25b7e.json"
          PKR_VAR_ssh_public_key_path: "ssh-key.pem.pub"

        run: packer build packer-image.pkr.hcl