name: Build Packer Image

on:
  workflow_dispatch: 

jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Packer
        uses: hashicorp/setup-packer@v3

      - name: Initialize Packer
        run: packer init packer-image.pkr.hcl

      - name: Set up SSH key
        run: |
          cat ${{ secrets.SSH_KEY }} | base64 --decode > ssh-key.pem
          ls -la

      - name: Validate Packer template
        run: packer validate packer-image.pkr.hcl

      - name: Build Packer image
        env:
          GOOGLE_CREDENTIALS: project-2024-2-e9ea57e25b7e.json
        run: packer build packer-image.pkr.hcl